# AlignParameters:
#   Enabled: false

# Encoding:
#   Enabled: false

LineLength:
  Max: 160

# HashSyntax:
#   EnforcedStyle: hash_rockets

# MethodLength:
#   Max: 30

# CyclomaticComplexity:
#   Max: 16

# ParameterLists:
#   Enabled: false

# ClassLength:
#   Max: 117

