rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic .
  - bundle exec rubocop
